server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: service-goods
  thymeleaf:
    prefix: classpath:/WEB-INF/view/
    suffix: .html

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8081/users/current
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:8081/oauth/token
      grant-type: client_credentials,password
      scope: server