server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 配置此项可通过http://localhost:8080/{大写服务名}/url 进行负载均衡调用
          lower-case-service-id: true # 配置此项可使用小写服务名路由
      routes:
      - id: goodsService
        uri: lb://GOODS
        predicates:
          - Path=/goods/**
        filters:
          - StripPrefix=1
      - id: auth
        uri: lb://AUTH
        predicates:
          - Path=/auth/**
        filters:
          - StripPrefix=1
# 使用手动配置服务的方式负载均衡
#    nacos:
#      discovery:
#        server-addr: http://localhost:8761/eureka/
#      config:
#        server-addr: 192.168.2.107:8848
#        file-extension: yml

#      routes:
#        - id: service_goods
#          uri: lb://service-goods #lb://服务名
#          predicates:
#            - Path=/goods/**
#          filters:
#            - StripPrefix=1
#        - id: service_order
#          uri: lb://service-order
#          predicates:
#            - Path=/order/**
#          filters:
#            - StripPrefix=1

#service-goods:
#  ribbon:
#    listOfServers: localhost:8764,localhost:8765
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#security:
#  oauth2:
#    client:
#      access-token-uri: http://localhost:8081/oauth/token
#      user-authorization-uri: http://localhost:8081/oauth/authorize
#      client-id: gateway
#    resource:
#      user-info-uri: http://localhost:8081/users/current
#      prefer-token-info: false

logging:
  level:
    org.springframework.cloud.gateway: debug


