spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.2.107:8848
      config:
        server-addr: 192.168.2.107:8848
        file-extension: yml
    gateway:
      routes:
        - id: business-account
          uri: lb://service-goods #lb://服务名
          #        uri: http://localhost:8081/business-account
          predicates:
            - Path=/goods
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        - id: business-account
          uri: lb://service-goods
          #        uri: http://localhost:8082/business-account/
          predicates:
            - Path=/goods
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
server:
  port: 8080
