server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

# spring-cloud-D版本之后需要手动打开feign断路器
feign:
  hystrix:
    enabled: true

spring:
  application:
    name: service-load-balance